# Generated by Django 5.0.6 on 2024-06-09 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul')),
                ('waktu_mulai', models.DateTimeField(verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.DateTimeField(verbose_name='Waktu Selesai')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
