# Generated by Django 5.0.6 on 2024-06-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_kandidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidat',
            name='pemilihan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kandidats', to='dashboard.pemilihan'),
        ),
    ]
