# Generated by Django 5.0.6 on 2024-06-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_kandidat_pemilihan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidat',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
