# Generated by Django 5.0.6 on 2024-06-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_kandidat_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.kandidat')),
                ('pemilih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pemilih')),
                ('pemilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pemilihan')),
            ],
            options={
                'unique_together': {('pemilih', 'pemilihan')},
            },
        ),
    ]
