# Generated by Django 5.0.6 on 2024-06-15 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilihan',
            name='pemilih',
            field=models.ManyToManyField(blank=True, related_name='pemilihan', to='dashboard.pemilih'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='kandidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.kandidat'),
        ),
    ]
