# Generated by Django 5.0.6 on 2024-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_pemilihan_pemilih_alter_voting_kandidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilihan',
            name='is_election_closed',
            field=models.BooleanField(default=False, verbose_name='Pemilihan Ditutup'),
        ),
    ]
