# Generated by Django 5.0.6 on 2024-06-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_kandidat_no_urut'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilih',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemilih',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='nama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='nim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='org_hima',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='org_ukm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='prodi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
