# Generated by Django 5.0.6 on 2024-06-21 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_pemilih_private_key_pemilih_public_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarPemilihTerpilih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemilih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pemilih')),
                ('pemilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pemilihan')),
            ],
        ),
    ]
