# Generated by Django 5.0.6 on 2024-06-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_daftarpemilihterpilih'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together=set(),
        ),
    ]
