# Generated by Django 5.0.6 on 2024-06-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_voting_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together={('pemilih', 'pemilihan')},
        ),
    ]
