# Generated by Django 5.0.6 on 2024-06-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_voting_encrypted_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='encrypted_data',
        ),
    ]
