# Generated by Django 5.0.6 on 2024-06-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_timestamp_voting_waktu_voting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='nama_kandidat_dekripsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
