# Generated by Django 5.0.6 on 2024-07-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_voting_nama_kandidat_dekripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemilih',
            name='nim',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
